# Vagrant file for running steamy demo locally.

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :forwarded_port, guest: 9484, host: 9484
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.synced_folder "../", "/home/vagrant/steamy"

  config.vm.provider "virtualbox" do |v|
    v.name = "Steamy Demo Vagrant"
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "shell" do |s|
    s.path = "./provision.sh"
  end
end
